### PR TITLE
SQLite DBConnection

### PR DESCRIPTION
**Pull request by scouten**

### CODE REVIEW

**Comment by scouten** [comment]
@fishcakez: FYI working on this as a way of approaching #29. Very much a work-in-progress that will probably take me a few days to complete. Am I at least on a reasonable track here?

**Comment by scouten** [comment]
@tchoutri if you are looking for an opportunity to jump in, perhaps you could try adding more of the tests from https://github.com/elixir-ecto/postgrex/blob/f773f8d4b88565aea435c6651b711ebfce74c9c2/test/query_test.exs (note: intentionally old version) and resolving any issues that come up. I'm probably out of the code until 1700 UTC Monday (9am US/Pacific).

**Comment by tchoutri** [comment]
Uh, I am facing something weird with `hackney` (pulled in by `coverex`), and [this stacktrace](https://gist.github.com/tchoutri/349b1a292d8af25034a1eb7349cad99e) doesn't speak to me.
It only fails when I'm running the tests

**Comment by fishcakez** [comment]
@tchoutri which versions of rebar3, elixir and hex?

**Comment by tchoutri** [comment]
@fishcakez =)

```Shell
$ mix --version
Erlang/OTP 19 [erts-8.1.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Mix 1.4.0
```

```Shell
$ rebar3 --version
rebar 3.0.0-beta.4+build.155.ref350fcd9 on Erlang/OTP 19 Erts 8.1.1
```

```Shell
 mix hex.info
Hex:    0.15.0
Elixir: 1.4.0
OTP:    19.1.6

Built with: Elixir 1.3.4 and OTP 18.3.4.4
```

**Comment by fishcakez** [comment]
Maybe update `rebar3` (and rm `_build`) because its old?

**Comment by tchoutri** [comment]
@fishcakez totally worked! thanks =)

**Comment by scouten** [comment]
@tchoutri sorry I was sound asleep when you wrote. @fishcakez thx for the help!

FWIW I am still running 1.3.4 on the machine I'm using for this dev effort.

Back in the code for the next few hours at least. DM me on Elixir Slack (@scouten) if you want to coordinate.

**Comment by scouten** [comment]
@fishcakez @tchoutri @supernullset I think the db_connection layer is built up enough that it's ready for use. (In other words, #29 should now be unblocked.) I'd appreciate a review of the architecture here. There are definitely some rough edges as indicated by the *TODO* comments, but the general direction should be there. Remember that this is attempting to match parity with the comparable version of Postgrex from early January 2016, not (yet) the current version.

I'll wait until Saturday afternoon US time for reviews; if no concerns raised by then, I'll merge and move on to #29.

Thanks very much for any attention you can give this! Appreciate the encouragement and support thus far.

**Pull request merged**
