### PR TITLE
Advance to "Use DBConnection" commit.

### PR DESCRIPTION
**Pull request by scouten**
This is where https://github.com/elixir-ecto/ecto/pull/1186 is merged in Ecto.

Postgrex went through the following changes in (approximately) this timeframe:

https://github.com/elixir-ecto/postgrex/compare/573aa1031aec0adb90f8be2ac5687daf2165299e...f773f8d4b88565aea435c6651b711ebfce74c9c2

### CODE REVIEW

**Comment by scouten** [comment]
@fishcakez: Would love some guidance on this one. If you look at the diffs in [lib/sqlite_ecto/connection.ex](https://github.com/scouten/sqlite_ecto2/pull/29/files#diff-92fad3d09210c997e8d03399546b96bd), you'll see a couple of "not sure what to do here" errors. I've identified potentially-relevant Postgrex diffs in the description above, but haven't had time to review them deeply. (May do that later tonight if I get time at keyboard later.)

Thanks in advance for any hints you can offer.

**Comment by scouten** [comment]
Looks like I need to write a Protocol module. 🙂

**Comment by fishcakez** [comment]
To be honest I am not sure what the best approach is here for sqlite. DBConnection is designed to be used with a `#Port<..>`, where the DBConnection callback module has direct access to that port and one process can safely close the port while another process is using it. If possible you would want sqlitex to use `DBConnection` and access a port. It might be possible to mimic a port with the sqlitex GenServer. I am unsure how well the NIF implementation will handle the caller exiting abruptly.

**Comment by scouten** [comment]
FWIW I am seeing sporadic aborts when running the test that look like this:

```
Assertion failed: (length == 0 && "Attempting to destroy a non-empty queue."), function queue_destroy, file c_src/queue.c, line 81.
```

**Comment by scouten** [comment]
@fishcakez I went ahead and merged this, but I would ❤️ 💚 💜  a post-hoc review on this change.

**Pull request merged**
