### PR TITLE
Add Elixir 1.4 to the text matrix.

### PR DESCRIPTION
**Pull request by scouten**
Now that @tchoutri has fixed the existing 1.4 warnings (thank you!), let's keep it going.

### CODE REVIEW

**Comment by scouten** [comment]
Shoot. Compiler warnings from 1.4 in Ecto code are causing the build to fail. Can the warning be disabled selectively?

**Comment by tchoutri** [comment]
I don't know if it's possible, better ask @josevalim ?

**Comment by josevalim** [comment]
On Elixir v1.4 we don't compile dependency with warnings I believe?

**Comment by scouten** [comment]
@josevalim yes, that's been my experience. The situation here is a little more complicated because we're directly including some of Ecto's files as though they were part of _this_ library (integration tests, notably) and it is those files that are getting caught up in `--warnings-as-errors`. As of now, this library is still using an old version of Ecto, so it's not really feasible to go fix the warnings in Ecto.

**Comment by scouten** [comment]
@tchoutri @josevalim thx for your interest. I wound up finding a minimal solution to the problem, which was to tweak the compiler settings just before calling `Code.require` on the relevant Ecto code.

**Pull request merged**
